# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'docker_nodejs_demo'

steps:
- task: Docker@2
  displayName: Build image from Dockerfile
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

- task: CmdLine@2
  inputs:
    script: |
      curl -s -k -u $(PCUSER):$(PCPASS) $PC_CONSOLE/api/v1/util/twistcli -v -o $(Build.SourcesDirectory)/twistcli
      chmod +x $(Build.SourcesDirectory)/twistcli
  displayName: "Install twistcli from Prisma Cloud Console"
- task: CmdLine@2
  displayName: Prisma Cloud - Twistcli Scan
  inputs:
    script: ‘$(Build.SourcesDirectory)/twistcli images scan --address $PC_CONSOLE -u $(PCUSER) -p $(PCPASS) --details $(imageName)’